### ISSUE TITLE
How to close an event source?

### ISSUE THREAD

**Issue by willydouhard** [launchdarkly/rust-eventsource-client#45]
Hello,

I did not find a method on the client or stream to close the event source connection.

I am quite new to Rust so I might miss something basic here.

Thanks!

**Comment by cwaldren-ld** [comment]
Hi @willydouhard, thank you for the question and welcome to the Rust community!

The client returns an asynchronous [stream](https://rust-lang.github.io/async-book/05_streams/01_chapter.html) (`BoxStream<Result<SSE>>`), which will terminate the connection once dropped. There is no explicit "close" method.

[Dropping](https://doc.rust-lang.org/rust-by-example/trait/drop.html) happens automatically when a resource goes out of scope; if you're familiar with destructors in other languages it's the same concept.

If you want to, Rust also allows you to manually call `drop(thing)` before the end of scope. Not necessary for most use-cases but it is an option.

**Comment by willydouhard** [comment]
Thank you for the warm welcome :)

I was not familiar with this concept, it makes much more sense now!

**Comment by cwaldren-ld** [comment]
I'll close this, but feel free to file another if you have any other issues or questions.
