### ISSUE TITLE
Infinite loop in rare conditions

### ISSUE THREAD

**Issue by spolu** [launchdarkly/rust-eventsource-client#46]
Here's a piece of code that uses event-source and leads in rare cases to an infinite loop:
https://github.com/dust-tt/dust/blob/fbced883d7e62d8c69624c5d19e48dbe9d8e9708/core/src/providers/openai.rs#L189-L332

I was able to profile the program and got the following flamegraph. Looks like it's looping inside of eventsource-client?
![test](https://user-images.githubusercontent.com/15067/218997125-052f5e6a-0379-4d2f-9685-e4e407fc951a.svg)

**Comment by spolu** [comment]
Maybe it's caused by the fact that I have retries deactivated?
https://github.com/launchdarkly/rust-eventsource-client/blob/main/eventsource-client/src/client.rs#L469-L475

**Comment by keelerm84** [comment]
I'm sorry you are experiencing this issue!

In both the event source library, and in the example you provided, there are several bits of logging information which might help us uncover some more insight into when this is happening.

Can you please provide some sample logging output when this issue occurs?

**Comment by spolu** [comment]
No logging at all (no HERE, no UNEXPECTED). Which is mind boggling to me :/

How can I activate the lib debug logging?

**Comment by keelerm84** [comment]
We use the `log` crate for logging. So you just need to initialize some logger that is compatible with that (e.g. `env_logger`) and then run your app with the appropriate `RUST_LOG=evensource=trace` level.

**Comment by spolu** [comment]
Will do that and report, hopefully stumbling on it again quickly

**Comment by spolu** [comment]
(Depends a lot on health state of OpenAI API 😅)

**Comment by cwaldren-ld** [comment]
Hi @spolu, just checking in, were you able to gather any logging for this issue?

**Comment by spolu** [comment]
The issue vanished by adding ReconnectOptions: https://github.com/dust-tt/dust/blob/main/core/src/providers/openai.rs#L241-L246

That does not resolve the whole problem. But at least that's an interesting hint.
