### ISSUE TITLE
Heartbeat Is Treated As Invalid Event

### ISSUE THREAD

**Issue by blheatwole** [launchdarkly/rust-eventsource-client#68]
According to the  [spec](https://html.spec.whatwg.org/multipage/server-sent-events.html#authoring-notes) that this library was based upon, servers may send an empty comment as a heartbeat.  The [Rocket implementation](https://github.com/rwf2/Rocket/blob/469f3942eb6567c2fdad7308350ee23dade030e9/core/lib/src/response/stream/sse.rs#L484) does this.

Below is a sample stream when connected to a Rocket server. The only message is a single `data:bheatwole` which is followed by an empty line to complete the event. The single `:` lines come exactly 30s apart and are not followed by an additional newline.

```
PS C:\Users\bheatwole> curl -v http://localhost:8000/api/events
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/events HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: text/event-stream
< cache-control: no-cache
< expires: 0
< server: Rocket
< permissions-policy: interest-cohort=()
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< transfer-encoding: chunked
< date: Tue, 05 Dec 2023 12:36:54 GMT
<
:
data:bheatwole

:
:
:
:

```
When eventsource-client tries to parse this kind of stream, it continually restarts the stream with this line being hit: [event_parser.rs line:267](https://github.com/launchdarkly/rust-eventsource-client/blob/b6e61d6bed5d7733666a351ae5d5359bd879cdee/eventsource-client/src/event_parser.rs#L267C17-L267C88)

The single colon as heartbeat behavior seems to be supported by the spec, so I think the correct place to file an issue is here and not with Rocket.

I'm willing to submit a PR for this, but I'd like to know how you want to handle it. We could:
1. Silently drop lines consisting of a single colon
2. Issue a SSE::Comment("")
3. Not change the library and force Rocket to change
4. Have a configuration flag `EmptyCommentBehavior` that gives you one of those options (Drop, Deliver, NotAllowed)

Choosing 1 would treat heartbeats like a protocol detail and not expose them to the user. Option 2 would let the user see the heartbeats, but force them to handle them in some way. If you choose option 3, I would likely find an alternate ES implementation or possibly do a private fork. In my opinion, option 4 adds complexity without much value, and so I would lean towards 1 or 2.

What are your thoughts?

**Comment by keelerm84** [comment]
Thank you for raising this issue and for providing some options on how we might proceed. I think option 2 is the most appropriate for this library.

The spec states that comments can be ignored. However, we have made the choice to expose them as well as actual events in case consumers want to leverage them in some way. Since I can't anticipate whether or not someone might want an empty comment, I think it's best to pass it back to the consumer and let them decide.

**Comment by blheatwole** [comment]
Sound good. I'll get going on the PR

**Comment by blheatwole** [comment]
The issue was, of course, in my code. This library is handling the `:` heartbeat correctly.

I was running the main loop like this: `while let Some(message) = client.stream().next().await { ... }` when it should have been
```
let mut stream = client.stream();
while let Some(message) = stream.next().await { ... }
```

The previous version of my code was forcing a reconnect on every loop. Sorry for the trouble.

(BTW, the library already does option 2. I discovered that while trying to write a failing test)
