### ISSUE TITLE
Ability to get the body when status code != 200

### ISSUE THREAD

**Issue by spolu** [launchdarkly/rust-eventsource-client#75]
What would be the best way to check the status code before streaming and getting a handle on the connection to parse the body in case where status code is not 200 ?

**Comment by keelerm84** [comment]
Thank you for opening up that PR. I'll keep all conversation on that thread so we don't split any discussion.

**Comment by keelerm84** [comment]
You should now be able to accomplish this with v0.13.0. An error of `UnexpectedResponse` will now include both a `Response` object include the status and header information, along with an `ErrorBody` type, which you can use to retrieve the body of the error.
